function [freqmeas,Vgmeas,Vomeas] = ...
              importfile_problem6(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [freqmeas,Vgmeas,Vomeas] = IMPORTFILE(FILE) reads data from the first
%   worksheet in the Microsoft Excel spreadsheet file named FILE and
%   returns the data as column vectors.
%
%   [freqmeas,Vgmeas,Vomeas] = IMPORTFILE(FILE,SHEET) reads from the
%   specified worksheet.
%
%   [freqmeas,Vgmeas,Vomeas] = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads
%   from the specified worksheet for the specified row interval(s). Specify
%   STARTROW and ENDROW as a pair of scalars or vectors of matching size
%   for dis-contiguous row intervals. To read to the end of the file
%   specify an ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [freqmeas,Vgmeas,Vomeas] = ...
%   importfile_problem6('ELEN100L_Project_1_Measured_Results.xlsx', ...
%                       'Sheet1',2,81);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/11/25 16:25:18

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 81;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, ...
                      sprintf('A%d:C%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, ...
                      sprintf('A%d:C%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x), ...
             raw); % Find non-numeric cells
raw(R) = {NaN};    % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
freqmeas = data(:,1);
Vgmeas = data(:,2);
Vomeas = data(:,3);

